name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Build and test the app
      run: |
        docker build -t devops-project .
        docker run -p 3000:3000 devops-project npm test
